# Generated by Django 3.2.4 on 2021-07-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contact',
            field=models.CharField(default='Not entered', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='gharNo',
            field=models.CharField(default='Not entered', max_length=5),
        ),
    ]
